### ISSUE TITLE
Contains function unable to match array

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1793]
When processing the template function `contains` array inputs are not able to match and return false.

> I am not sure if its 100% related to this but since Monday I began to face the issues with Azure.Defender rule. Basicity I am getting Azure.Defender rule failed with message stating that I have `pricingTier` set to `'Free'`. Based on [this rule source code](https://github.com/Azure/PSRule.Rules.Azure/blob/main/src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.yaml) I understand that it is expecting to find `'standard'` but actually its already set to be `'standard'`. Please see a screenshot with few error messages examples.
> 
> ![image](https://user-images.githubusercontent.com/49737301/195104402-49329df7-a7ed-4156-a0d6-43867b0b5906.png)
> 
> Also I am attaching a [**module** ](https://gist.github.com/s1mb414/a40b922d2e37279207061b7680a3ecdb) and a [**parameters** ](https://gist.github.com/s1mb414/2d3df1463466c008036526ffa53ac3ce) so it would be easier to replicate the issue. 
> 
> Any ideas why PSrule could see pricingTier as 'Free' instead of 'standard' while using attached module and parameter file?

_Originally posted by @s1mb414 in https://github.com/Azure/PSRule.Rules.Azure/issues/1632#issuecomment-1274738034_

**Comment by Rycardas** [comment]
Hello, I have exact same issue as described above. While using same code [https://gist.github.com/s1mb414/a40b922d2e37279207061b7680a3ecdb](url) to evaluate individual resourses price tier. `resource securityCenterPricing 'Microsoft.Security/pricings@2018-06-01' = [for name in disableSecurityCenterFor: {
  name: name
  properties: {
    pricingTier: contains(enableSecurityCenterFor, name) ? 'Standard' : 'Free'
  }
}]` While evaluating, contains function returns "false" (Free tier) instead of expected "true" (Standard). Please see a screenshot with few error messages. 
![image](https://github.com/Azure/PSRule.Rules.Azure/assets/55191252/5ca7f4f5-87c9-4190-b8b5-308e482b8adb)
