### ISSUE TITLE
Update Azure.AKS.Version to 1.26.6

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2404]
### Suggested rule

AKS support for Kubernetes 1.27 is now GA.

### Pillar

Reliability

### Additional context

https://azure.microsoft.com/updates/generally-available-kubernetes-127-support-in-aks

**Comment by BernieWhite** [comment]
@BenjaminEngeset Good call out. We generally follow one minor version behind the latest GA because, officially if customers choose the "stable" release they will not get the latest GA, they will get n-1. i.e. currently `1.26.6`. This is defined by the AKS team so it makes sense to align this rule.

Customers can override the `AZURE_AKS_CLUSTER_MINIMUM_VERSION` value to a later version if they like but since "stable" is `1.26.6` now that 1.27.x is out we should bump this rule to `1.26.6`.

I hope that this reasoning makes sense.
