### ISSUE TITLE
[BUG] Export-AzPolicyAssignmentRuleData unable to export Azure policy as PSRule (The function "field" was not found) [Microsoft policy ID: fbb99e8e-e444-4da0-9ff1-75c92f5a85b2]

### ISSUE THREAD

**Issue by Marc013** [Azure/PSRule.Rules.Azure#2725]
### Description of the issue

Unable to export policy assignment data to PSRule.

PolicyDefinitionId: /providers/Microsoft.Authorization/policyDefinitions/fbb99e8e-e444-4da0-9ff1-75c92f5a85b2
DisplayName: Storage account containing the container with activity logs must be encrypted with BYOK

### Error messages

An error occurred evaluating expression '[contains(field('Microsoft.Insights/logProfiles/storageAccountId'), subscription().Id)]' line 11105. The function "field" was not found.

### Reproduction

Exporting policy assignment data of Microsoft policy  _/providers/Microsoft.Authorization/policyDefinitions/fbb99e8e-e444-4da0-9ff1-75c92f5a85b2_

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.33.2

### Additional context

This bug is related to #1323

**Comment by BernieWhite** [comment]
@Marc013 Currently it's not possible for PSRule to coordinate over different resources, so this is not enforceable in code.

We will add this policy definition to the ignore list so that there is no error and a warning will be generated instead as the fix.

In the interim you can set the [AZURE_POLICY_IGNORE_LIST](https://azure.github.io/PSRule.Rules.Azure/setup/configuring-rules/#azure_policy_ignore_list) configuration option.
