### ISSUE TITLE
[RULE] Virtual Network Gateways should have customer controlled maintenance configurations enabled/configured

### ISSUE THREAD

**Issue by jtracey93** [Azure/PSRule.Rules.Azure#2910]
### Suggested rule

Virtual Network Gateways should have customer controlled maintenance configurations enabled/configured as per: https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#configure-customer-controlled-expressroute-gateway-maintenance

### Pillar

Reliability

**Comment by BenjaminEngeset** [comment]
:shipit:

**Comment by BenjaminEngeset** [comment]
Hi @BernieWhite,

I wanted to discuss some technical details regarding the configuration and attachment, which involve two different extension resource types. Since extension resources cannot be declared within the parent resource, how does PSRule identify their relationship with the gateway resource type object?

I believe the PSRule engine performs a specific action because we have existing rules for this (which I created but can’t recall the internal logic now).

Does the PSRule engine essentially place the extension resources within the resources block of the parent resource, given that the extension resource has a scope property that maps to an object PSRule will analyze also? Or does it create a dummy parent object based on the scope property of the extension resource and then put extension resources that maps to the same parent dummy object under the resources block of the parent dummy object?

**Comment by BernieWhite** [comment]
https://learn.microsoft.com/en-gb/azure/well-architected/reliability/metrics
