### ISSUE TITLE
[RULE] Can "Associate a maintenance configuration" rule also belong to the Reliability pillar?

### ISSUE THREAD

**Issue by jeanchg** [Azure/PSRule.Rules.Azure#2925]
### Existing rule

Azure.VM.MaintenanceConfig

### Suggested rule

Can this rule also belong to the reliability pillar baseline?
As per [this VM recommendation in the "Reliability Hub"](https://learn.microsoft.com/en-us/azure/reliability/reliability-virtual-machines?tabs=graph#-use-maintenance-configurations-for-the-vm), this is also considered a High Priority **Reliability** recommendation.

### Pillar

Reliability

### Additional context

For context, in AVM, to enforce Reliability recommendations through our CI, we leverage the Azure.Pillar.Reliability baseline, and we're currently missing this one.

**Comment by BernieWhite** [comment]
@jeanchg Technically we could but it's not something we do today. But there has been some movement in the WAF since this rule was created so it's probably best targeted to reliability instead of op ex anyway.

I propose we just move the rule to the reliability pillar, and also it's not a preview feature anymore so we can update the docs and remove the preview flag.

**Comment by jeanchg** [comment]
thanks @BernieWhite I wasn't sure having one rule in several pillars was something being done. Thanks for clarifying.
Happy if it moves to reliability pillar and without the preview flag! Thank you.
