### ISSUE TITLE
IaaS SQL Servers only use premium disks

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#9]
Check that IaaS SQL VMs only use premium disk.

**Comment by bengeset96** [comment]
Still relevant to this day.

Should we opt for premium on only data disks, or os disk as well?

At last, premium ssd v2 is suited for sql server in general, but currently it has so many obscur limitations so i dont think its a really good idea to recommend this to customers, so fail on premium ssd v2 as well even if the customer has configured it?

**Comment by bengeset96** [comment]
@BernieWhite

**Comment by BernieWhite** [comment]
@bengeset96 The original thought was related to performance efficiency. I think if a customer uses Premium, Premium V2 or ultra-disks that addresses the rule. A recommendation to the premium SSD or greater is enough.

**Comment by BernieWhite** [comment]
> @BernieWhite
> 
> I'm also wondering if we should target `Microsoft.Compute/virtualMachines` and focus on the publisher `MicrosoftSQLServer`, but that is probably not safe enough to assume `Microsoft.SqlVirtualMachine/sqlVirtualMachines`.
> 
> Perhaps there is a way in PSRule to get both resources onto the pipeline in the same TargetObject?

Targeting by publisher is probably the best. It's not really possible to see both related objects.

**Comment by bengeset96** [comment]
@BernieWhite 

Sounds great. This means that we will be able to test osDisk and dataDisks defined within `storageProfile`.

We wont be able to target disks from `Microsoft.Compute/disks` or `Microsoft.Storage/storageAccounts` I assume since there is nothing here that gives us the information we're seeking, but that option is most likely not so widely used for this scenario.
